### ISSUE TITLE
Use type state pattern

### ISSUE THREAD

**Issue by clarkmcc** [libp2p/rust-yamux#143]
I'm coming from the Go yamux so I understand how the Go library works, however, I'm wondering if it makes sense given the Rust type system to prevent server-side connections from being able to call client-only methods. Right now, the API will let me call client-only methods like `open_stream` even though I'm working with a server connection. It seems like Rust's type system can better express the distinction between a server and client connection. I'm not a Rust expert, so I don't know how to pull this off, but it does feel like the API could be better.

**Comment by thomaseizinger** [comment]
Both sides in yamux can open streams, that is an explicit goal, see "Features": https://github.com/hashicorp/yamux

The API could still be a lot better and I am currently working on that (see #142).

**Comment by thomaseizinger** [comment]
There will be type states to reflect the actual connection state: Active, Closing, etc.

**Comment by clarkmcc** [comment]
Oh, interesting, I was not aware of that. I'm sorry, pardon my ignorance then!

**Comment by thomaseizinger** [comment]
> Oh, interesting, I was not aware of that. I'm sorry, pardon my ignorance then!

No worries :)

Closing here as completed then!
