### ISSUE TITLE
Consider increasing `receive_window` default

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-yamux#162]
In order to exhaust the [_bandwidth delay product_](https://en.wikipedia.org/wiki/Bandwidth-delay_product) of a connection, i.e. to maximize the amount of data in-flight, so to say the amount of data temporarily stored on the _wire_, one needs a receive window size in accordance to the connection properties.

Example:
- Consider two nodes in two different datacenters, across the US (e.g. AWS us-east-1 and us-west-2).
- Latency between the two nodes is 60 ms.
- They each have a link of 25 Gbit/s.
- The bandwidth delay product would be: `60ms * 25Gbit/s = 187.5 Mbyte`

(Learn more about the setup on https://github.com/libp2p/test-plans/pull/184.)

In other words, one needs a `187.5 Mbyte` receive window to fully utilize the underlying network between the two machines.

Currently we set the default receive window per stream to `256 Kbyte`. This is the default value according to the Yamux specification.

https://github.com/libp2p/rust-yamux/blob/34dcb97a6e2b8fdb3bb4cbb5c47e4506d2ef4ff2/yamux/src/lib.rs#L43

https://github.com/libp2p/rust-yamux/blob/34dcb97a6e2b8fdb3bb4cbb5c47e4506d2ef4ff2/yamux/src/lib.rs#L116-L127

At the same time we set a maximum buffer size per stream to `1 Mbyte`. This can not possibly be used, i.e. the buffer can never grow larger than the receive window, unless one uses `WindowUpdateMode::OnReceive`, which I consider a bad option in every case as it breaks backpressure. The default value is probably still from a time when `WindowUpdateMode::OnReceive` was the default, i.e. before https://github.com/libp2p/rust-yamux/commit/ab4fe4566e759ca8bea814cc1a4eff93038de5bb.

https://github.com/libp2p/rust-yamux/blob/34dcb97a6e2b8fdb3bb4cbb5c47e4506d2ef4ff2/yamux/src/lib.rs#L120

In the above scenario, when using the default values, one can achieve roughly `20 Mbit/s` **on a single stream**. Using a receive window of `16 Mbyte` bumps this to `300 Mbit/s`. Note that with the default one can still exhaust the bandwidth delay product, one just has to use multiple streams.

There is a downside to choosing a large receive window. The larger the receive window, the more memory an adversary can make the local node allocate, potentially leading to the local node to run out of memory. 

So what value should we choose instead of the current `256 Kbyte`? I don't know. Ideally one could configure a maximum per stream and a maximum per connection such that one can exhaust the bandwidth delay product on a single stream, or using multiple streams. ([See QUIC and in particular quinn as a role model.](https://github.com/quinn-rs/quinn/blob/98f5fe2a3fabb9ff991f8c831e8d43de76985ff3/quinn-proto/src/config.rs#L27-L33))

What does go-libp2p do? They set a `16 Mbyte` maximum receive window, but given their resource manager they have more fine grained control of how much memory an adversary can allocate.

https://github.com/libp2p/go-yamux/blob/e584a210c72651b67829477b4b4285cae25b1a1b/const.go#L115-L120

**Comment by thomaseizinger** [comment]
> What does go-libp2p do? They set a `16 Mbyte` maximum receive window, but given their resource manager they have more fine grained control of how much memory an adversary can allocate.

So "all" we'd need is a connection-wide setting on how big all combined buffers are allowed to be, right? As long as stay under the configured limit, new streams could grow their receive window to 16 MB. Once we have reached a certain number of streams, that number would go down.

Thoughts?

**Comment by thomaseizinger** [comment]
> we would need to block new outgoing and incoming streams

I would have just reduced the initial window size down to the default. In other words, the configured max size is not about total RAM consumption but just about the size of the window updates.

That should avoid any locking / waking and still allow for streams to enjoy a large receive buffer.

**Comment by mxinden** [comment]
> > we would need to block new outgoing and incoming streams
> 
> I would have just reduced the initial window size down to the default. In other words, the configured max size is not about total RAM consumption but just about the size of the window updates.

I don't understand. With the above, as an attacker I could exhaust the connection limit on a single stream and then open all remaining allowed streams with the default window size no? More concretely I would ramp up the first stream to a receive window of 16 MB and then open `8192 - 1` with the default window of `256 KB`.

**Comment by mxinden** [comment]
As expected, increasing the stream receive window to 16 MB (`set_receive_window(16 * 1024 * 1024)`) has a significant impact on throughput performance. In the last libp2p-perf run its a median of ~ 32 Mbit/s vs ~ 1.23 Gbit/s.

![newplot(13)](https://github.com/libp2p/rust-yamux/assets/7047859/e79f75de-622a-4eef-b3df-b8434b47e01b)

(Produced via https://github.com/libp2p/test-plans/pull/316.)

I see three ways forward:

1. Leave as is, missing out on significant throughput performance gains.
2. Simply adjusting the defaults, i.e. lower max-stream-count and increase max-stream-receive-window.
3. Implement dynamic window sizing like go-libp2p does, see https://github.com/libp2p/go-yamux/issues/9.


> So "all" we'd need is a connection-wide setting on how big all combined buffers are allowed to be, right?

Yes. Plus, what I forgot above, we need some heuristic on when to grant a stream a higher window, i.e. when to go beyond the 256 KB default. See as a comparison the go-libp2p heuristic based on RTT https://github.com/libp2p/go-yamux/issues/9.
