### ISSUE TITLE
chore: remove `WindowUpdateMode::OnReceive`

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-yamux#175]
I suggest we remove `WindowUpdateMode::OnReceive` in favor of always using (not just defaulting to) `WindowUpdateMode::OnRead`.

I can not think of a use-case where one would want `OnReceive` over `OnRead`. Anyone?

Removing `OnReceive` will simplify our codebase.

https://github.com/libp2p/rust-yamux/blob/93b70626f7f3d83f97951d9cd5c2951500088f0d/yamux/src/lib.rs#L66-L76

**Comment by thomaseizinger** [comment]
Sounds good to me!

Perhaps make a point-release deprecating it first :)
