### ISSUE TITLE
`poll_new_outbound` without sending data results in no `inbound` stream

### ISSUE THREAD

**Issue by robinhundt** [libp2p/rust-yamux#185]
Hi, thanks for this crate!

I'm currently trying to write a higher-level wrapper around this library. As a starting point I wrapped the `Connection` into its own struct which also contains the receiving end of an `mpsc::channel` over commands. The corresponding `spawn` method selects on `poll_new_inbound` and the channel.
The idea was, a user can send a message over the command channel which results in both a new outbound channel being created, as well as a new inbound channel. The other party executes the same code and polls for an outbound and inbound channel.

After establishing the channels, I wanted to send a message from both parties on their outbound channel and receive it on the others inbound channel.
(Side Note: I know that an established Stream is bidirectional, but in the future, I want to start sending from both parties as soon as `poll_new_outbound` completes, without waiting for the ACK).

Unfortunately, I hit a problem and my test deadlocked. After quite some time, I found the underlying issue:
A stream returned by `poll_new_outbound` without sending data on this stream results in no `inbound` stream on the side of the socket.

The simplified flow looked roughly like this:
```
+---------------------------------+         +---------------------------------+
|                                 |         |                                 |
|                P0               |         |                P1               |
|                                 |         |                                 |
|                                 |         |                                 |
| outbound =  poll_new_outbound() |         | outbound =  poll_new_outbound() |
|                                 |         |                                 |
| inbound  =  poll_new_inbound()  |         | inbound  =  poll_new_inbound()  |
|                                 |         |                                 |
|                                 |         |                                 |
| outbound.send(0)                |         | outbound.send(0)                |
|                                 |         |                                 |
| msg = inbound.recv()            |         | msg = inbound.recv()            |
|                                 |         |                                 |
+---------------------------------+         +---------------------------------+
```
(Note: `poll_new_inbound` was continuously polled in a background task)

Because `poll_new_inbound` only resolves once the first message on the stream is sent, my code never got to the `outbound.send()` and deadlocked.

While I understand that it might makes sense to delay establishing the inbound stream, this should definitely be documented.
If the above is not wrong and the issue actually lies somewhere else, I could maybe send a documentation PR (but I'm not sure when I'll have the time for this).

**Comment by thomaseizinger** [comment]
> A stream returned by `poll_new_outbound` without sending data on this stream results in no `inbound` stream on the side of the socket.

Yes this is very much on purpose. Yamux streams are only a logical construct. They just frame the data you want to send. Without sending data, we can't send a message about the new stream.

This design makes them cheap / almost free. The intent is that you create lots of short-lived streams, each of them scoped to a unit of communication for your application, like one HTTP request and its response for example. Your application can then comfortably run those in parallel and yamux takes care of de-multiplexing them on the wire. (Note that you will still perceive HoL blocking because yamux only works on top of TCP which will still stall a lot of your packets in unreliable networks.)

If you are building a new application, I'd suggest looking into QUIC instead. It is superior over TCP + yamux in pretty much every way.

**Comment by robinhundt** [comment]
> If you are building a new application, I'd suggest looking into QUIC instead. It is superior over TCP + yamux in pretty much every way.

Thanks for this pointer! Initially I wanted to base my library on yamux because it seemed simpler than most QUIC implementations and I wanted to have the option of using plain TCP instead of TLS. However, after looking into QUIC some more, I decided to base my library on [s2n-quic](https://github.com/aws/s2n-quic) and like it so far. I didn't realise QUIC had stream multiplexing built-in.

From my side, this issue can be closed. Thanks!
